---
- hosts: all
  become: true
  gather_facts: true
  tasks: 
    - name: Install packages using yum
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - extras
          - vsftpd
          - php
